import "../globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { redirect } from "next/navigation";
import { AuthProvider } from "./AuthProvider";
import { readAuth } from "./readAuth";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const auth = await readAuth();
  if (auth === null || auth.user.company.name === null) {
    redirect("/setup");
  }

  return (
    <UserProvider>
      <AuthProvider auth={auth}>{children}</AuthProvider>
    </UserProvider>
  );
}
